name       : zziplib
version    : 0.13.67
release    : 2
source     :
    - https://github.com/gdraheim/zziplib/archive/v0.13.67.tar.gz : 1278178bdabac832da6bbf161033d890d335a2e38493c5af553ff5ce7b9b0220
license    : LGPL-2.0
component  : programming.library
summary    : Lightweight library for extracting data zip files
description: |
    Lightweight and usable library for extracting data from files archived into a single zip file.  Uses the free subset of the zlib algorithm.
builddeps  :
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
