name       : zziplib
version    : 0.13.66
release    : 1
source     :
    - https://github.com/gdraheim/zziplib/archive/v0.13.66.tar.gz : 59b18c7c4ed348ba8d63fa7e194e6b012cd94197265b7a7b3afb539d8206bd7d
license    : LGPL-2.0
component  : programming.library
summary    : Lightweight library for extracting data zip files
description: |
    Lightweight and usable library for extracting data from files archived into a single zip file.  Uses the free subset of the zlib algorithm.
builddeps  :
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
check      : |
    %make check
install    : |
    %make_install
