name       : zziplib
version    : 0.13.72
release    : 5
source     :
    - https://github.com/gdraheim/zziplib/archive/v0.13.72.tar.gz : 93ef44bf1f1ea24fc66080426a469df82fa631d13ca3b2e4abaeab89538518dc
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Lightweight library for extracting data zip files
description: |
    Lightweight and usable library for extracting data from files archived into a single zip file.  Uses the free subset of the zlib algorithm.
networking : yes # check
builddeps  :
    - xmlto
environment: |
    unset LD_PRELOAD
setup      : |
    %cmake_ninja -DBUILD_TESTS=ON
build      : |
    %ninja_build
    %ninja_build man
install    : |
    %ninja_install
    install -dm00755 $installdir/usr/share/man/man3
    install -Dm00644 solusBuildDir/docs/man3/*.3 $installdir/usr/share/man/man3
check      : |
    %ninja_build tests || :
patterns   :
    - devel :
        - /usr/share/man/man3
